"""
Auto-generated by gui_recorder.py
"""
import time
from gui_live import connect_application

# TODO: update title to match your target window
s = connect_application(title="...")
s.focus()

s.press('f7')
time.sleep(15.8)
s.click('Turn on Caret Browsing?||Window')
s.click('Turn on Caret Browsing?||Window')
time.sleep(3.2)
s.click('Turn on Caret Browsing?||Window->Yes||Button')
time.sleep(3.7)
s.click('Calculator||Window->Number pad||Group->Seven||Button')
time.sleep(2.1)
s.click('Calculator||Window->Number pad||Group->One||Button')
s.click('Calculator||Window->Standard operators||Group->Plus||Button')
s.click('Desktop 1||Pane->tk||Pane')
time.sleep(4.2)
s.click('Calculator||Window->Close Calculator||Button')
