from __future__ import annotations

from typing import Optional
from pywin_gui_inspector.recorder.events import ClickEvent, TypeEvent, HotkeyEvent


class ScriptExporter:
    """Converts recorded events to a DesktopSession-based Python script.

    Inspects a list of recorder event objects and produces a Python source
    file that replays the same interactions using the live-session API.

    Attributes:
        SHELL_WINDOWS: Set of lower-cased window names that are considered
            part of the Windows shell (taskbar, search, etc.) and excluded
            when determining the primary application window.
    """

    SHELL_WINDOWS: frozenset[str] = frozenset({
        "program manager", "taskbar", "start", "cortana", "search",
        "task view", "notification center", "action center",
        "windows input experience",
    })

    @staticmethod
    def primary_window(events: list) -> str:
        """Determines the most-seen application window name from the event list.

        Extracts the top-level window name from each event's path, filters
        out shell/system windows and the recorder itself, then returns the
        name that appeared most frequently.

        Args:
            events: A list of recorder event objects
                (:class:`~pywin_gui_inspector.recorder.events.ClickEvent`,
                :class:`~pywin_gui_inspector.recorder.events.TypeEvent`, or
                :class:`~pywin_gui_inspector.recorder.events.HotkeyEvent`).

        Returns:
            The most-common application window name as a string, or
            ``"..."`` if no qualifying names are found.
        """
        from collections import Counter
        names: list[str] = []
        for ev in events:
            path = getattr(ev, "path", "")
            if not path:
                continue
            name = path.split("->")[0].split("||")[0].strip()
            if not name:
                continue
            nl = name.lower()
            if nl.startswith("desktop ") or nl in ScriptExporter.SHELL_WINDOWS or nl.startswith("gui recorder"):
                continue
            names.append(name)
        return Counter(names).most_common(1)[0][0] if names else "..."

    @staticmethod
    def generate(events: list) -> str:
        """Generates a Python script that replays the recorded event sequence.

        Inserts ``time.sleep()`` calls between events whose timestamps differ
        by 1.5 to 30 seconds to approximate the original interaction pacing.
        Click events are mapped to ``s.click()`` or ``s.right_click()``,
        type events to ``s.set_text()`` or ``s.send_keys()``, and hotkey
        events to ``s.hotkey()`` or ``s.press()``.

        Args:
            events: An ordered list of recorder event objects to replay.

        Returns:
            A string containing a complete, ready-to-run Python script
            ending with a newline.
        """
        title = ScriptExporter.primary_window(events)
        lines = [
            '"""', "Auto-generated by gui_recorder.py", f"Primary app: {title}", '"""',
            "import time",
            "from pywin_gui_inspector.live import DesktopSession",
            "",
            f"# To target a specific app: connect_application(title={title!r})",
            "s = DesktopSession()",
            "",
        ]
        prev_ts: Optional[float] = None
        for ev in events:
            if prev_ts is not None:
                gap = ev.timestamp - prev_ts
                if 1.5 < gap < 30:
                    lines.append(f"time.sleep({gap:.1f})")
            prev_ts = ev.timestamp

            if isinstance(ev, ClickEvent):
                m = "right_click" if ev.button == "right" else "click"
                lines.append(f"s.{m}({ev.path!r})")
            elif isinstance(ev, TypeEvent):
                lines.append(f"s.set_text({ev.path!r}, {ev.text!r})" if ev.path
                              else f"s.send_keys({ev.text!r})")
            elif isinstance(ev, HotkeyEvent):
                lines.append(f"s.press({ev.keys[0]!r})" if len(ev.keys) == 1
                              else f"s.hotkey({', '.join(repr(k) for k in ev.keys)})")

        return "\n".join(lines) + "\n"